name: Compile Sketch

# The workflow will run on push and pull requests to the repository
on:
  push:
    branches:
      - main
      - compiles
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main
    strategy:
      matrix:
        arduino-boards-fqbn: 
          - arduino:avr:uno
    
        include:
          - arduino-boards-fqbn: arduino:avr:uno
            sketch-names: main.ino
          
      fail-fast: false

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Arduino library directory
        run: mkdir -p $HOME/Arduino/libraries

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      - name: Copy Custom Libraries to work directory
        run: |
          cp -r $GITHUB_WORKSPACE/main/src/MovementCustom $GITHUB_WORKSPACE/MovementCustom
          cp -r $GITHUB_WORKSPACE/main/src/VisionSystemCustomo $GITHUB_WORKSPACE/VisionSystemCustom
          cp -r $GITHUB_WORKSPACE/main/src/NavigationCustom $GITHUB_WORKSPACE/NavigationCustom
          cp -r $GITHUB_WORKSPACE/main/src/PayloadCustom $GITHUB_WORKSPACE/PayloadCustom
          cp -r $GITHUB_WORKSPACE/main/src/ParamsCustom $GITHUB_WORKSPACE/ParamsCustom
      
      - name: Show current directory and contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing contents of the current directory:"
          ls -lah
          echo "Listing contents of the src directory:"
          ls -lah src/
          echo "Listing contents of the GitHub workspace directory:"
          ls -lah $GITHUB_WORKSPACE
          echo "Listing contents of the Arduino libraries directory:"
          ls -lah $HOME/Arduino/libraries/

        # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          sketch-names: ${{ matrix.sketch-names }}
