name: Compile Sketch

# The workflow will run on push and pull requests to the repository
on:
  push:
    branches:
      - main
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples
    runs-on: ubuntu-latest
    env:
      REQUIRED_LIBRARIES: Movement,Navigation,ENES100,Payload
    strategy:
      matrix:
        arduino-boards-fqbn: 
          - arduino:avr:uno
    
        include:
          - arduino-boards-fqbn: arduino:avr:uno
            sketch-names: main.ino
          
      fail-fast: false

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          sketch-names: ${{ matrix.sketch-names }}
