name: Compile Sketch

# The workflow will run on push and pull requests to the repository
on:
  push:
    branches:
      - main
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/main
    strategy:
      matrix:
        arduino-boards-fqbn: 
          - arduino:avr:uno
    
        include:
          - arduino-boards-fqbn: arduino:avr:uno
            sketch-names: main.ino
          
      fail-fast: false

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      - name: Create Arduino library directory
        run: mkdir -p $HOME/Arduino/libraries

      - name: Create symlinks for custom libraries
        run: |
          ln -s $GITHUB_WORKSPACE/main/src/Movement $HOME/Arduino/libraries/Movement
          ln -s $GITHUB_WORKSPACE/main/src/ENES100 $HOME/Arduino/libraries/ENES100
          ln -s $GITHUB_WORKSPACE/main/src/Navigation $HOME/Arduino/libraries/Navigation
          ln -s $GITHUB_WORKSPACE/main/src/Payload $HOME/Arduino/libraries/Payload

        # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          sketch-names: ${{ matrix.sketch-names }}
